# Documentation generator based on MkDocs
# Automatically documents API references
# References:
#   https://www.mkdocs.org/
#   https://mkdocstrings.github.io/recipes/

site_name: ACED-IDP Documentation

nav:
- index.md
- getting-started.md
- Requirements:
  - requirements/gen3-client.md
  - requirements/gen3_util.md
- Use Cases & Workflows:
  - workflows/creating-project.md
  - workflows/upload.md
  - workflows/download.md
- Status Monitor ↗: https://aced-idp.github.io/status-monitor

plugins:
  - search
  - macros

repo_url: https://github.com/ACED-IDP/aced-idp.github.io
repo_name: ACED-IDP/aced-idp.github.io
  
theme:
  name: "material"
  features:
    - navigation.expand
    - navigation.indexes 
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true