# Documentation generator based on MkDocs
# Automatically documents API references
# References:
#   https://www.mkdocs.org/
#   https://mkdocstrings.github.io/recipes/

site_name: ACED-IDP Documentation

nav:
- index.md
- Getting Started:
  - requirements.md
  - workflows/quick-start-guide.md
- Use Cases & Workflows:
  - workflows/creating-project.md
  - Submitting Data:
    - workflows/add-files.md
    - Metadata:
        - data-model/introduction.md
        - workflows/metadata.md
        - data-model/integration.md
    - workflows/status.md
    - workflows/commit-push.md
  - Consuming Data:
    - workflows/clone.md
  - Exploring Data:
    - workflows/portal-explore.md
    - workflows/portal-download.md
    - workflows/query.md
  - Utilities:
    - workflows/approve-requests.md
    - workflows/add-users.md
  - Experimental Features:
    - workflows/tabular.md
  - workflows/common-errors.md
- Status Monitor ↗: https://aced-idp.github.io/status-monitor

plugins:
  - search
  - macros

repo_url: https://github.com/ACED-IDP/aced-idp.github.io
repo_name: ACED-IDP/aced-idp.github.io
  
theme:
  name: material
  palette:
    - scheme: default
      primary: custom
  features:
    - navigation.indexes 
    - navigation.footer
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css